name: Double
version: ${version}
main: com.axodouble.Double
api-version: '1.21'
description: Double, the utility plugin.
author: Axodouble
website: https://github.com/Axodouble/Double
commands:
  arena:
    description: Arena command
    usage: /arena <list|delete|public> [name]
  pvp:
    description: PVP command
    usage: /pvp <player|accept>
  gvg:
    description: GVG command
    usage: /gvg <player|accept|invite>
  mod:
    description: Moderation commands
    usage: /mod <ban> <arena|pvp> <player>
  leaderboard:
    description: Show the top fighters in the server
    usage: /leaderboard
    aliases: [ top ]
  profile:
    description: Show your profile
    usage: /profile
  stats:
    description: Show your profile
    usage: /profile
  version:
    description: Show the plugin version
    usage: /version
  sit:
    description: Sit command
    usage: /sit
  marry:
    description: Marry command
    usage: /marry <player>
  divorce:
    description: Divorce command
    usage: /divorce
  accept:
    description: Accept command
    usage: /accept
  jump:
    description: Jump command
    usage: /jump
    aliases: [ j ]
  day:
    description: Day command
    usage: /day
  night:
    description: Night command
    usage: /night
  discord:
    description: Discord command
    usage: /discord
  race:
    description: A command to change your race
    usage: /race
permissions :
  double.discord:
    description: "Access to the /discord command that is set in the config.yml"
    default: true
  double.time:
    description: "Access to the /day and /night commands"
    default: op
    children:
      double.time.day:
        description: "Access to the /day command"
        default: op
      double.time.night:
        description: "Access to the /night command"
        default: op
      double.time.*:
        description: "Access to all time commands"
        default: op
  double.arena:
    description: "Access to the /arena command"
    default: true
  double.pvp:
    description: "Access to the /pvp command"
    default: true
  double.gvg:
    description: "Access to the /gvg command"
    default: true
  double.mod:
    description: "Access to the /mod command"
    default: op
  double.sit:
    description: "Access to the /sit command and to sit on blocks"
    default: true
  double.marry:
    description: "Access to the /marry, /accept and /divorce commands"
    default: true
  double.jump:
    description: "Access to the /jump command"
    default: op
  double.races:
    description: "Access to the /race command"
    default: true
    children:
      double.races.become:
        description: "Access to become a race with /race become <race>"
        default: true
      double.races.become.*:
        description: "Access to specific races"
        default: true
      double.races.reload:
        description: "Access to reload the races"
        default: op
      double.races.restore:
        description: "Access to restore all races"
        default: op