name: Ceraia
version: ${version}
main: com.ceraia.Ceraia
api-version: '1.21.4'
description: Ceraia, the utility plugin.
author: Axodouble
website: https://github.com/Ceraia/Minecraft
commands:
  arena:
    description: Join the arena.
    usage: /arena
  pvp:
    description: Join the pvp arena.
    usage: /pvp
  gvg:
    description: Join the gvg arena.
    usage: /gvg
  leaderboard:
    description: Show the leaderboard.
    usage: /leaderboard
  profile:
    description: Show your profile.
    usage: /profile
  version:
    description: Show the version of the plugin.
    usage: /version
  sit:
    description: Sit where ever you want.
    usage: /sit
  marry:
    description: Marry someone you love.
    usage: /marry <player>
  divorce:
    description: Divorce who you're married to.
    usage: /divorce
  jump:
    description: Teleport to the destination you are looking at.
    usage: /jump
    aliases: [ j ]
  day:
    description: Turn the world to day.
    usage: /day
  night:
    description: Turn the world to night.
    usage: /night
  noon:
    description: Turn the world to noon.
    usage: /noon
  discord:
    description: Get a link to the discord server
    usage: /discord
  race:
    description: A command to change your race
    usage: /race
permissions :
  double.discord:
    description: "Access to the /discord command that is set in the config.yml"
    default: true
  double.time:
    description: "Access to the /day and /night commands"
    default: op
    children:
      double.time.day:
        description: "Access to the /day command"
        default: op
      double.time.night:
        description: "Access to the /night command"
        default: op
      double.time.*:
        description: "Access to all time commands"
        default: op
  double.sit:
    description: "Access to the /sit command and to sit on blocks"
    default: true
  double.marry:
    description: "Access to the /marry command"
    default: true
  double.jump:
    description: "Access to the /jump command"
    default: op
  double.races:
    description: "Access to the /race command"
    default: true
    children:
      double.races.become:
        description: "Access to become a race with /race become <race>"
        default: true
      double.races.become.*:
        description: "Access to specific races"
        default: true
      double.races.reload:
        description: "Access to reload the races"
        default: op
      double.races.restore:
        description: "Access to restore all races"
        default: op