name: Ceraia
version: ${version}
main: com.ceraia.Ceraia
api-version: '1.21'
description: Ceraia, the utility plugin.
author: Axodouble
website: https://github.com/Ceraia/Minecraft
commands:
  version:
    description: Show the version of the plugin.
    usage: /version
  sit:
    description: Sit where ever you want.
    usage: /sit
  marry:
    description: Marry someone you love.
    usage: /marry <player>
  divorce:
    description: Divorce who you're married to.
    usage: /divorce
  jump:
    description: Teleport to the destination you are looking at.
    usage: /jump
    aliases: [ j ]
  day:
    description: Turn the world to day.
    usage: /day
  night:
    description: Turn the world to night.
    usage: /night
  noon:
    description: Turn the world to noon.
    usage: /noon
  discord:
    description: Get a link to the discord server
    usage: /discord
  race:
    description: A command to change your race
    usage: /race
permissions :
  ceraia.discord:
    description: "Access to the /discord command that is set in the config.yml"
    default: true
  ceraia.time:
    description: "Access to the /day and /night commands"
    default: op
    children:
      ceraia.time.day:
        description: "Access to the /day command"
        default: op
      ceraia.time.night:
        description: "Access to the /night command"
        default: op
      ceraia.time.*:
        description: "Access to all time commands"
        default: op
  ceraia.sit:
    description: "Access to the /sit command and to sit on blocks"
    default: true
  ceraia.marry:
    description: "Access to the /marry command"
    default: true
  ceraia.jump:
    description: "Access to the /jump command"
    default: op
  ceraia.races:
    description: "Access to the /race command"
    default: true
    children:
      ceraia.races.become:
        description: "Access to become a race with /race become <race>"
        default: true
      ceraia.races.become.*:
        description: "Access to specific races"
        default: true
      ceraia.races.reload:
        description: "Access to reload the races"
        default: op
      ceraia.races.restore:
        description: "Access to restore all races"
        default: op